[phases.setup]
nixPkgs = []

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install"
]

[phases.build]
cmds = [
  "if [ -f next.config.mjs ]; then sed -i 's/{[[:space:]]*type:[[:space:]]*\"host\"[[:space:]]*}/{ type: \"host\", value: \".*\" }/g' next.config.mjs; fi",
  "if [ -f next.config.js ]; then sed -i 's/{[[:space:]]*type:[[:space:]]*\"host\"[[:space:]]*}/{ type: \"host\", value: \".*\" }/g' next.config.js; fi",
  "pnpm build"
]

[start]
cmd = "pnpm start"
