FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm

COPY . .

# corrige bug do next (host header)
RUN sed -i 's/type: "host"/type: "host", value: ".*"/g' next.config.mjs || true
RUN sed -i "s/type: 'host'/type: 'host', value: '.*'/g" next.config.mjs || true

RUN pnpm install
RUN pnpm build

EXPOSE 3000

CMD ["pnpm", "start"]
